// This code was autogenerated by ChatGPT
// background.js

// Start checks on installation
chrome.runtime.onInstalled.addListener(() => {
  console.log("Close Tabs by Keywords extension installed.");

  // Default list of strings to check against in the URLs.
  let defaultStringsToCheck = ["youtube.com"];
  chrome.storage.sync.set({ stringsToCheck: defaultStringsToCheck });

  // Set up an interval to check for specified strings in tabs every 10 seconds (adjust as needed).
  setInterval(() => {
    checkTabsForKeywords();
  }, 10000); // 10 seconds
});

// Start checks on browser startup
chrome.runtime.onStartup.addListener(() => {
  console.log("Close Tabs by Keywords extension started with the browser.");

  // On startup, check tabs for keywords immediately.
  setInterval(() => {
    checkTabsForKeywords();
  }, 10000); // 10 seconds
});

// Run checks
function checkTabsForKeywords() {
  chrome.tabs.query({}, (tabs) => {
    chrome.storage.sync.get(["stringsToCheck"], (result) => {
      let stringsToCheck = result.stringsToCheck || defaultStringsToCheck;
      for (let i = 0; i < tabs.length; i++) {
        let tabUrl = tabs[i].url;
        if (tabUrl && stringsToCheck.some((str) => tabUrl.includes(str))) {
          chrome.tabs.remove(tabs[i].id);
        }
      }
    });
  });
}

