// This file was generated by ChatGPT
// popup.js

document.addEventListener("DOMContentLoaded", function () {
  let keywordsInput = document.getElementById("keywordsInput");
  let saveKeywordsButton = document.getElementById("saveKeywordsButton");

  // Load existing keywords from storage
  chrome.storage.sync.get(["stringsToCheck"], (result) => {
    let currentKeywords = result.stringsToCheck || [];
    keywordsInput.value = currentKeywords.join(", ");
  });

  // Save keywords when the button is clicked
  saveKeywordsButton.addEventListener("click", function () {
    let newKeywords = keywordsInput.value.split(",").map((keyword) => keyword.trim());
    chrome.storage.sync.set({ stringsToCheck: newKeywords });
  });
});

